apiVersion: apps/v1
kind: Deployment
metadata:
  name: t11-test
  labels:
    app: t11-test
spec:
  selector:
    matchLabels:
      app: t11-test
  template:
    metadata:
      labels:
        app: t11-test
    spec:
      containers:
      - name: t11-test
        image: gitlab.sdu.dk:5050/semester-project-e2021/team-11/template/testapi:latest
        resources:
          limits:
            cpu: 100m
            memory: 0.5Gi
          requests:
            cpu: 100m
            memory: 0.5Gi
      imagePullSecrets:
      - name: sdugitlab